# Generated by Django 4.2.7 on 2026-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
