# Generated by Django 4.2.7 on 2026-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_at_purchase',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('half', '0.5 KG'), ('1kg', '1 KG'), ('2kg', '2 KG')], default='half', max_length=4),
            preserve_default=False,
        ),
    ]
