# Generated by Django 6.0.3 on 2026-03-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIQuery',
        ),
    ]
