# Generated by Django 5.1.1 on 2026-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_instructor_course_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or other video URL for this course', null=True),
        ),
    ]
